fix: checking the cache dependencies

diff --git a/.github/workflows/upper-build.yml b/.github/workflows/upper-build.yml
--- a/.github/workflows/upper-build.yml
+++ b/.github/workflows/upper-build.yml
@@ -25,7 +25,14 @@ jobs:
                 #   go-version: '1.22'
                 go-version-file: ./demo-files/upper/go.mod
                 cache-dependency-path: ./demo-files/upper/go.sum
-            - run: go mod download
+            - run: |
+                if [ ! -f ./demo-files/upper/go.mod ]; then
+                  echo "go.mod file not found!"
+                  exit 1
+                fi
+                go mod download
+ 
+                go mod download
 
             - name: build and test the go project
               run: |
